"""empty init

Revision ID: 64934708f362
Revises: 
Create Date: 2023-10-04 17:49:18.189819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64934708f362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
